ActionController::Base.send(:extend, Ponteggio::ControllerScaffold)
ActionView::Base.send(:include, Ponteggio::PageHelper)
ActionView::Base.send(:include, Ponteggio::IndexHelper)
ActionView::Base.send(:include, Ponteggio::ValueHelper)
ActionView::Base.send(:include, Ponteggio::FormHelper)
